### PR TITLE
Added auth code accessibility from VC init completion

### PR DESCRIPTION
**Pull request by Nicolas-Isaza**
-created authorizationCode property to InstagramLoginResponse
-can now access authorization code after signing user in

### CODE REVIEW

**Comment by rbaumbach** [comment]
What is the motivation for exposing this auth code?

The purpose of this "Simple" InstagramOAuthViewController is to keep it as simple as possible and not expose anything to a consumer if it is not absolutely necessary.  If I'm not mistaken, the only data required to use the Instagram API once a user has allowed an app access is the access token.

**Comment by Nicolas-Isaza** [comment]
The access token may expire. Storing the authorization code allows generation of a new access token without presenting the view controller.

**Comment by rbaumbach** [comment]
Currently Instagram access tokens don't expire, and if they do (but it doesn't look like there are plans to at the moment but could change obviously), you really should have the user re-attempt a login and get a new auth code.

http://stackoverflow.com/questions/22753170/instagram-access-token-expire

**Comment by Nicolas-Isaza** [comment]
I did not know their access tokens don't expire. Your implementation is fine then. Thanks.

**Pull request closed without merging**
